credentials_signup:
    path: /credentials
    controller: App\Application\API\SignUpController
    methods: [POST]

credentials_signin:
    path: /credentials
    controller: App\Application\API\SignInController
    methods: [GET]