users_signup:
    path: /users
    controller: App\UserAccountManagement\Application\API\SignUpController
    methods: [POST]

users_signin:
    path: /users
    controller: App\UserAccountManagement\Application\API\SignInController
    methods: [GET]