users_signup:
    path: /users
    controller: App\Application\UserAccountManagement\API\SignUpController
    methods: [POST]

users_signin:
    path: /users
    controller: App\Application\UserAccountManagement\API\SignInController
    methods: [GET]