players_signup:
    path: /players
    controller: App\PlayerAccountManagement\Application\API\SignUpController
    methods: [POST]

players_signin:
    path: /players
    controller: App\PlayerAccountManagement\Application\API\SignInController
    methods: [GET]