credentials_signup:
    path: /credentials
    controller: App\Application\CredentialsManagement\API\SignUpController
    methods: [POST]

credentials_signin:
    path: /credentials
    controller: App\Application\CredentialsManagement\API\SignInController
    methods: [GET]