players_signup:
    path: /players
    controller: App\Application\PlayerAccountManagement\API\SignUpController
    methods: [POST]

players_signin:
    path: /players
    controller: App\Application\PlayerAccountManagement\API\SignInController
    methods: [GET]