App\Infrastructure\Doctrine\CredentialsDataMapper:
    type: entity
    table: 'credentials'
    repositoryClass: App\Infrastructure\Doctrine\Adapter\CredentialsRepository
    id:
        id:
            type: uuid
    fields:
        email:
            type: string
            length: 191
            unique: true
        hashedPassword:
            type: string
            length: 191
