App\Infrastructure\Doctrine\TokenDataMapper:
    type: entity
    table: 'token'
    repositoryClass: App\Infrastructure\Doctrine\Adapter\TokenRepository
    id:
        id:
            type: uuid
    fields:
        credentialsId:
            type: uuid
        value:
            type: string
            length: 191
            unique: true
        expireAt:
            type: datetime_immutable
        type:
            type: string
            length: 191
