App\PlayerAccountManagement\Infrastructure\Doctrine\PlayerDataMapper:
    type: entity
    table: 'player'
    repositoryClass: App\PlayerAccountManagement\Infrastructure\Doctrine\Adapter\PlayerRepository
    id:
        id:
            type: uuid
    fields:
        email:
            type: string
            length: 191
            unique: true
        hashedPassword:
            type: string
            length: 191
        name:
            type: string
            length: 191
            unique: true
